# Hangi PHP sürümünü ve web sunucusunu kullanmak istediğinizi belirtin
# Örneğin: php:8.2-apache veya php:8.1-fpm
FROM php:8.2-apache

# Çalışma dizinini ayarlayın
WORKDIR /var/www/html

COPY . /var/www/html/

RUN docker-php-ext-install pdo pdo_mysql

RUN apt-get update && apt-get install -y curl
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer


CMD ["apache2-foreground"]
